package com.gitboy.shiro.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.gitboy.shiro.pojo.Function;


@Mapper
public interface FunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    int insert(Function record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    Function selectByPrimaryKey(Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    List<Function> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_functions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Function record);
    
    /**
     * ���ݽ�ɫid��ѯȨ���б�
     * @param list
     * @return
     */
    public List<Function> findByRoleIds(List<Integer> list);

	List<Function> findFunctionByUserId(Integer userId);
}